# Generated by Django 4.0.4 on 2022-05-04 19:55

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_choice', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Product Size',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('excerpt', models.TextField(null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='product_images/default.png', upload_to='product_images/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('in_stock', models.BooleanField(default=True)),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store_products.category')),
                ('size', models.ManyToManyField(blank=True, to='store_products.productsizechoice')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created',),
            },
        ),
    ]
