# Generated by Django 4.0.4 on 2022-05-08 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0005_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('created',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('created',), 'verbose_name': 'sub-category', 'verbose_name_plural': 'sub-categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
