# Generated by Django 4.0.4 on 2022-05-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
